# Generated by Django 5.2.13 on 2026-04-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='school code')),
                ('name', models.CharField(db_index=True, max_length=120, verbose_name='school name')),
                ('education_office', models.CharField(blank=True, max_length=80)),
                ('support_office', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, db_index=True, max_length=120)),
                ('establishment', models.CharField(blank=True, max_length=30)),
                ('school_type', models.CharField(blank=True, max_length=80)),
                ('day_night', models.CharField(blank=True, max_length=20)),
                ('founded_on', models.DateField(blank=True, null=True)),
                ('anniversary_on', models.DateField(blank=True, null=True)),
                ('lot_address', models.CharField(blank=True, max_length=255)),
                ('road_address', models.CharField(blank=True, max_length=255)),
                ('road_address_detail', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('fax', models.CharField(blank=True, max_length=30)),
                ('homepage_url', models.URLField(blank=True, max_length=255)),
                ('gender_type', models.CharField(blank=True, max_length=30)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('is_paused', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'region'], name='core_school_name_b3c42e_idx')],
            },
        ),
    ]
