# Generated by Django 5.2.13 on 2026-04-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_guestbookentry_post_comment_postrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='deletion_password_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='deletion_password_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts/%Y/%m/'),
        ),
    ]
