# Generated by Django 5.2.13 on 2026-04-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_comment_deletion_password_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deletion_password_hash',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deletion_password_hash',
        ),
    ]
