# Generated by Django 5.2.13 on 2026-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_comment_deletion_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board_type',
            field=models.CharField(choices=[('general', '일반'), ('verified', '인증')], db_index=True, default='general', max_length=20),
        ),
    ]
